### ISSUE TITLE
Not working for me , libczmq  directory is empty 

### ISSUE THREAD

**Issue by wajahat414** [crcunningham/zeromq_ios_libraries#1]
I tried Running Build.sh But it is not working , its completing but not giving  binaries for libczmq

**Comment by crcunningham** [comment]
Debug it and put up a PR.

**Comment by wajahat414** [comment]
I tried compiling with IOS sdk 16.2, it is giving errors

**Comment by wajahat414** [comment]
Can you rebuild with updated ios SDK ??
